services:
  backend:
    image: gear_backend
    environment:
      - AILTIRE_HOST=backend
      - AILTIRE_PORT=3000
      - AILTIRE_OPENAI_KEY=sk-proj-...
    ports:
      - "3000:3000"
    networks:
      sibling:
        aliases:
          - backend
  web:
    image: gear_web
    ports:
      - '5173:5173'
    environment:
      - BACKEND_URL=http://backend:3000/web
    networks:
      - sibling
  ollama:
    image: gear_ollama
    ports:
      - '11434:11434'
    networks:
      sibling:
        aliases:
          - ollama

networks:
  sibling:
    driver: overlay
