services:
  backend:
    image: paidar/gear_backend
    environment:
      - AILTIRE_HOST=backend
      - AILTIRE_PORT=4000
      - AILTIRE_OPENAI_KEY=sk-proj-...
    ports:
      - "4000:4000"
    networks:
      sibling:
        aliases:
          - backend
  web:
    image: paidar/gear_web
    ports:
      - '5173:5173'
    environment:
      - BACKEND_URL=http://backend:4000/web
    networks:
      - sibling
  ollama:
    image: paidar/gear_ollama
    ports:
      - '11434:11434'
    networks:
      sibling:
        aliases:
          - ollama

networks:
  sibling:
    driver: overlay
    attachable: true
