@startuml

hide circle
hide empty  members

abstract class Element {
    +name : string
    +description : string
    +version: string
}

class Domain extends Element
class Layer extends Element
class SubLayer extends Element
class Component extends Element

@enduml